In [1]:
import pandas as pd
import numpy as np

'Q_2022.csv'
def preprocessing(file_path):
    print(f'===== 원데이터 불러오기 : {file_path}', '\n')
    raw_data = pd.read_csv(file_path, low_memory = False)
    print(f'원 데이터 : {raw_data.shape}')

    print('===== EM / LM / Z 세대 나누기 =====', '\n')
    raw_data = raw_data[raw_data['dq2'] >= 1981]

    conditions = [
    (raw_data['dq2'] >= 1981) & (raw_data['dq2'] <= 1988),
    (raw_data['dq2'] >= 1989) & (raw_data['dq2'] <= 1995),
    (raw_data['dq2'] >= 1996)
    ]
    
    choices = ['early_M', 'late_M', 'Z']
    
    data = raw_data.copy()
    data.loc[:, 'gen'] = np.select(conditions, choices, default=np.nan)
    print(f'세대 나눈 데이터 : {data.shape}')

    print('===== 불필요 데이터 삭제 1차 =====', '\n')
    remove_col = ['ID', 'q1_1_m1', 'q1_1_m2', 'q5_1_1', 'q5_2_1', 'q5_3_1',
             'q6_1_1', 'q6_2_1', 'q6_3_1', 'q6_4_1', 'A1', 'A2',
             'q9_m1', 'q9_m2', 'q9_m3', 'q13_1_1', 'q13_1_2', 'q13_1_3',
             'q17_m1', 'q17_m2', 'q18_m1', 'q18_m2', 'q28_m1', 'q28_m2', 'q28_m3',
             'B', 'q31_C1', 'q31_C2', 'q38_1', 'q38_2_m1', 'q38_2_m2',
             'dq7', 'DM2', 'DM3', 'DM4', 'DM6', 'DM7', 'WT', 'TWT', 'dq2']

    new_data = data.drop(remove_col, axis=1)
    print(f'세대 + 불필요 칼럼 처리 : {new_data.shape}')

    print('===== 역문항 처리 =====', '\n')
    # 역문항 처리
    columns_to_reverse = ['q8_5', 'q14_4', 'q19_5', 'q33_5', 'q33_6', 'q33_7', 'q33_8']
    
    def reverse(x):
        if x == 5:
            return 1
        elif x == 4:
            return 2
        elif x == 3:
            return 3
        elif x == 2:
            return 4
        else:
            return 5
    
    for column in columns_to_reverse:
        print(f'{column} 처리중...')
        new_data[column] = new_data[column].apply(reverse)

    # 차원 합치기
    print('\n', '===== 유사 문항 평균화 =====', '\n')
    new_data['resource'] = new_data[['q3_1', 'q3_2', 'q3_3']].mean(axis=1)
    new_data['job_autonomy'] = new_data[['q4_1', 'q4_2', 'q4_3']].mean(axis=1)
    new_data['recruitment'] = new_data[['q7_1', 'q7_2', 'q7_3', 'q7_4']].mean(axis=1)
    new_data['promotion'] = new_data[['q8_1', 'q8_2', 'q8_3', 'q8_4', 'q8_5']].mean(axis=1)
    new_data['job_rotation'] = new_data[['q10_1', 'q10_2', 'q10_3']].mean(axis=1)
    new_data['compensation_rewards'] = new_data[['q11_1', 'q11_2', 'q11_3', 'q11_4']].mean(axis=1)
    new_data['welfare'] = new_data[['q13_1', 'q13_2']].mean(axis=1)
    new_data['training'] = new_data[['q14_1', 'q14_2', 'q14_3', 'q14_4']].mean(axis=1)
    new_data['performance_capacity'] = new_data[['q15_1', 'q15_2', 'q15_3']].mean(axis=1)
    new_data['organizational_goals'] = new_data[['q19_1', 'q19_2', 'q19_3', 'q19_4', 'q19_5']].mean(axis=1)
    new_data['leadership'] = new_data[['q20_1', 'q20_2', 'q20_3', 'q20_4', 'q20_5', 'q20_6', 'q20_7']].mean(axis=1)
    new_data['decision_making'] = new_data[['q22_1', 'q22_2', 'q22_3', 'q22_4']].mean(axis=1)
    new_data['change_management'] = new_data[['q23_1', 'q23_2', 'q23_3']].mean(axis=1)
    new_data['collaboration_communication'] = new_data[['q24_1', 'q24_2', 'q24_3']].mean(axis=1)
    new_data['organizational_performance'] = new_data[['q25_1', 'q25_2']].mean(axis=1)
    new_data['performance_management'] = new_data[['q26_1', 'q26_2', 'q26_3', 'q26_4', 'q26_5']].mean(axis=1)
    new_data['job_performance'] = new_data[['q27_1', 'q27_2', 'q27_3']].mean(axis=1)
    new_data['public_service'] = new_data[['q30_1', 'q30_2', 'q30_3', 'q30_4', 'q30_5', 'q30_6']].mean(axis=1)
    new_data['organizational_citizenship_behavior'] = new_data[['q32_1', 'q32_2', 'q32_3', 'q32_4', 'q32_5']].mean(axis=1)
    new_data['innovative_behavior'] = new_data[['q33_1', 'q33_2', 'q33_3', 'q33_4', 'q33_5', 'q33_6', 'q33_7', 'q33_8']].mean(axis=1)
    new_data['public_service_values'] = new_data[['q34_1', 'q34_2', 'q34_3', 'q34_4', 'q34_5', 'q34_6', 'q34_7', 'q34_8']].mean(axis=1)
    new_data['commitment'] = new_data[['q35_1', 'q35_2', 'q35_3', 'q35_4']].mean(axis=1)
    new_data['job_satisfaction'] = new_data[['q36_1', 'q36_2', 'q36_3']].mean(axis=1)
    new_data['public_job_satisfaction'] = new_data[['q37_1', 'q37_2', 'q37_3', 'q37_4']].mean(axis=1)
    new_data['quality_of_life'] = new_data[['q39_1', 'q39_2']].mean(axis=1)

    print('===== 불필요 데이터 삭제 2차 =====', '\n')

    remove_col2 = [ "q3_1", "q3_2", "q3_3",
      "q4_1", "q4_2", "q4_3",
      "q7_1", "q7_2", "q7_3", "q7_4",
      "q8_1", "q8_2", "q8_3", "q8_4", "q8_5",
      "q10_1", "q10_2", "q10_3",
      "q11_1", "q11_2", "q11_3", "q11_4",
      "q13_1", "q13_2",
      "q14_1", "q14_2", "q14_3", "q14_4",
      "q15_1", "q15_2", "q15_3",
      "q19_1", "q19_2", "q19_3", "q19_4", "q19_5",
      "q20_1", "q20_2", "q20_3", "q20_4", "q20_5", "q20_6", "q20_7",
      "q22_1", "q22_2", "q22_3", "q22_4",
      "q23_1", "q23_2", "q23_3",
      "q24_1", "q24_2", "q24_3",
      "q25_1", "q25_2",
      "q26_1", "q26_2", "q26_3", "q26_4", "q26_5",
      "q27_1", "q27_2", "q27_3",
      "q30_1", "q30_2", "q30_3", "q30_4", "q30_5", "q30_6",
      "q32_1", "q32_2", "q32_3", "q32_4", "q32_5",
      "q33_1", "q33_2", "q33_3", "q33_4", "q33_5", "q33_6", "q33_7", "q33_8",
      "q34_1", "q34_2", "q34_3", "q34_4", "q34_5", "q34_6", "q34_7", "q34_8",
      "q35_1", "q35_2", "q35_3", "q35_4",
      "q36_1", "q36_2", "q36_3",
      "q37_1", "q37_2", "q37_3", "q37_4",
      "q39_1", "q39_2"]
    
    final_data = new_data.drop(remove_col2, axis=1)
    print(f'불필요 칼럼 처리2 : {final_data.shape}', '\n')

    print('===== 이직 의도 이진화 =====')
    conditions2 = [
    (final_data['q38'] <= 3),
    (final_data['q38'] > 3)
    ]
    
    choices2 = ['N', 'Y']
    
    final_data2 = final_data.copy()
    final_data2.loc[:, 'y'] = np.select(conditions2, choices2, default=np.nan)
    final_data2 = final_data2.drop(['q38'], axis=1)
    print(f'이직 의도 이진화 후 기존 열 처리 : {final_data2.shape}')
    print(f'결측치 : {final_data2.isnull().sum().sum()}', '\n')
    

    print('..... 전처리 전/후 레이블 길이 비교 .....')
    print(final_data['q38'].head())
    print(final_data2['y'].head())

    Z = final_data2[final_data2['gen'] == 'Z']
    EM = final_data2[final_data2['gen'] == 'early_M']
    LM = final_data2[final_data2['gen'] == 'late_M']
    
    Z_X = Z.drop(['y', 'gen'], axis=1)
    EM_X = EM.drop(['y', 'gen'], axis=1)
    LM_X = LM.drop(['y', 'gen'], axis=1)

    Z_y = Z['y']
    EM_y = EM['y']
    LM_y = LM['y']

    return Z_X, Z_y, LM_X, LM_y, EM_X, EM_y

In [2]:
Z_X, Z_y, LM_X, LM_y, EM_X, EM_y = preprocessing('Q_2022.csv')

===== 원데이터 불러오기 : Q_2022.csv

원 데이터 : (6170, 192)
===== EM / LM / Z 세대 나누기 =====

세대 나눈 데이터 : (3446, 193)
===== 불필요 데이터 삭제 1차 =====

세대 + 불필요 칼럼 처리 : (3446, 153)
===== 역문항 처리 =====

q8_5 처리중...
q14_4 처리중...
q19_5 처리중...
q33_5 처리중...
q33_6 처리중...
q33_7 처리중...
q33_8 처리중...

 ===== 유사 문항 평균화 =====

===== 불필요 데이터 삭제 2차 =====

불필요 칼럼 처리2 : (3446, 75)

===== 이직 의도 이진화 =====
이직 의도 이진화 후 기존 열 처리 : (3446, 75)
결측치 : 0

..... 전처리 전/후 레이블 길이 비교 .....
1    4
2    5
3    4
4    1
6    2
Name: q38, dtype: int64
1    Y
2    Y
3    Y
4    N
6    N
Name: y, dtype: object

In [3]:
from pycaret.classification import *

# 1. Z세대

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(Z_X, Z_y, test_size = 0.2, random_state = 42, shuffle = False)

In [110]:
print(f'X_train : {X_train.shape}, y_train 수 : {len(y_train)}')
print(f'X_test : {X_test.shape}, y_test 수 : {len(y_test)}')

X_train : (1196, 73), y_train 수 : 1196
X_test : (299, 73), y_test 수 : 299

In [111]:
y_test_num = [1 if y == 'Y' else 0 for y in y_test]

In [112]:
import numpy as np
import pandas as pd
from pycaret.classification import setup, compare_models, predict_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, roc_auc_score, recall_score, precision_score, f1_score, cohen_kappa_score, matthews_corrcoef

# 평가 지표를 저장할 데이터 구조 초기화
results = {model: [] for model in range(19)}  # 19개 모델을 저장할 딕셔너리

n_iterations = 100
for i in range(n_iterations):
    print(f"Iteration {i+1}/{n_iterations}")

    # PyCaret 설정
    clf1 = setup(data=X_train, target=y_train, verbose=False, html=False, session_id=i)

    # 모든 모델 비교
    best_models = compare_models(sort='AUC', n_select=19, fold=5, cross_validation=True, verbose=False)

    # 각 모델에 대한 예측 및 평가 지표 계산
    for model in best_models:
        predictions = model.predict(X_test)
        actual = y_test_num
        #pred_labels = predictions['prediction_label']
        #pred_scores = predictions['prediction_score']
        accuracy = accuracy_score(actual, predictions)
        auc = roc_auc_score(actual, predictions)
        recall = recall_score(actual, predictions)
        precision = precision_score(actual, predictions)
        f1 = f1_score(actual, predictions)
        kappa = cohen_kappa_score(actual, predictions)
        mcc = matthews_corrcoef(actual, predictions)

        model_name = model.__class__.__name__
        metrics = {
            'Accuracy': accuracy,
            'AUC': auc,
            'Recall': recall,
            'Precision': precision,
            'F1': f1,
            'Kappa': kappa,
            'MCC': mcc
        }

        # 결과 저장
        if model_name not in results:
            results[model_name] = []
        results[model_name].append(metrics)

# 평균 및 표준편차 계산
summary = {}
for model_name, metrics_list in results.items():
    summary[model_name] = {}
    for metric in ['Accuracy', 'AUC', 'Recall', 'Precision', 'F1', 'Kappa', 'MCC']:
        mean_val = np.mean([m[metric] for m in metrics_list])
        std_val = np.std([m[metric] for m in metrics_list])
        summary[model_name][metric] = {'Mean': mean_val, 'Std': std_val}

Iteration 1/100
Iteration 2/100
Iteration 3/100
Iteration 4/100
Iteration 5/100
Iteration 6/100
Iteration 7/100
Iteration 8/100
Iteration 9/100
Iteration 10/100
Iteration 11/100
Iteration 12/100
Iteration 13/100
Iteration 14/100
Iteration 15/100
Iteration 16/100
Iteration 17/100
Iteration 18/100
Iteration 19/100
Iteration 20/100
Iteration 21/100
Iteration 22/100
Iteration 23/100
Iteration 24/100
Iteration 25/100
Iteration 26/100
Iteration 27/100
Iteration 28/100
Iteration 29/100
Iteration 30/100
Iteration 31/100
Iteration 32/100
Iteration 33/100
Iteration 34/100
Iteration 35/100
Iteration 36/100
Iteration 37/100
Iteration 38/100
Iteration 39/100
Iteration 40/100
Iteration 41/100
Iteration 42/100
Iteration 43/100
Iteration 44/100
Iteration 45/100
Iteration 46/100
Iteration 47/100
Iteration 48/100
Iteration 49/100
Iteration 50/100
Iteration 51/100
Iteration 52/100
Iteration 53/100
Iteration 54/100
Iteration 55/100
Iteration 56/100
Iteration 57/100
Iteration 58/100
Iteration 59/100
Iteration 60/100
Iteration 61/100
Iteration 62/100
Iteration 63/100
Iteration 64/100
Iteration 65/100
Iteration 66/100
Iteration 67/100
Iteration 68/100
Iteration 69/100
Iteration 70/100
Iteration 71/100
Iteration 72/100
Iteration 73/100
Iteration 74/100
Iteration 75/100
Iteration 76/100
Iteration 77/100
Iteration 78/100
Iteration 79/100
Iteration 80/100
Iteration 81/100
Iteration 82/100
Iteration 83/100
Iteration 84/100
Iteration 85/100
Iteration 86/100
Iteration 87/100
Iteration 88/100
Iteration 89/100
Iteration 90/100
Iteration 91/100
Iteration 92/100
Iteration 93/100
Iteration 94/100
Iteration 95/100
Iteration 96/100
Iteration 97/100
Iteration 98/100
Iteration 99/100
Iteration 100/100

In [113]:
import pandas as pd

# summary 딕셔너리를 데이터프레임으로 변환
data_for_df = []
index_labels = []

for model_name, metrics in summary.items():
    for metric_name, metric_values in metrics.items():
        mean = metric_values['Mean']
        std = metric_values['Std']
        data_for_df.append(f"{mean:.4f} ± {std:.4f}")
        index_labels.append((model_name, metric_name))

# 인덱스 설정 (모델 이름과 메트릭 이름)
multi_index = pd.MultiIndex.from_tuples(index_labels, names=["Model", "Metric"])

# 데이터프레임 생성
df = pd.DataFrame(data_for_df, index=multi_index, columns=["Value"])

# 데이터프레임을 보기 좋게 조정 (unstack 사용)
df_unstacked = df.unstack(level='Metric')

# 지정된 순서
order = ["Accuracy", "AUC", "Recall", "Precision", "F1", "Kappa", "MCC"]

# 지정된 순서에 따라 열을 재정렬
df_unstacked = df_unstacked["Value"][order]

In [114]:
df_unstacked.iloc[18:41,:]

Metric,Accuracy,AUC,Recall,Precision,F1,Kappa,MCC
Model,,,,,,,
18,nan ± nan,nan ± nan,nan ± nan,nan ± nan,nan ± nan,nan ± nan,nan ± nan
AdaBoostClassifier,0.6743 ± 0.0203,0.6724 ± 0.0199,0.6510 ± 0.0306,0.6404 ± 0.0257,0.6451 ± 0.0213,0.3444 ± 0.0400,0.3449 ± 0.0400
CatBoostClassifier,0.6928 ± 0.0117,0.6922 ± 0.0116,0.6849 ± 0.0241,0.6557 ± 0.0153,0.6697 ± 0.0134,0.3830 ± 0.0233,0.3836 ± 0.0233
DecisionTreeClassifier,0.5962 ± 0.0284,0.5974 ± 0.0290,0.6109 ± 0.0501,0.5507 ± 0.0279,0.5786 ± 0.0336,0.1931 ± 0.0572,0.1946 ± 0.0582
DummyClassifier,0.4548 ± 0.0000,0.5000 ± 0.0000,1.0000 ± 0.0000,0.4548 ± 0.0000,0.6253 ± 0.0000,0.0000 ± 0.0000,0.0000 ± 0.0000
ExtraTreesClassifier,0.6801 ± 0.0156,0.6799 ± 0.0152,0.6774 ± 0.0283,0.6409 ± 0.0200,0.6581 ± 0.0165,0.3581 ± 0.0306,0.3590 ± 0.0304
GaussianNB,0.6733 ± 0.0085,0.6692 ± 0.0075,0.6241 ± 0.0222,0.6465 ± 0.0157,0.6346 ± 0.0089,0.3394 ± 0.0157,0.3400 ± 0.0160
GradientBoostingClassifier,0.6869 ± 0.0157,0.6854 ± 0.0157,0.6687 ± 0.0292,0.6523 ± 0.0193,0.6600 ± 0.0182,0.3699 ± 0.0313,0.3704 ± 0.0312
KNeighborsClassifier,0.6085 ± 0.0173,0.5957 ± 0.0172,0.4545 ± 0.0492,0.5924 ± 0.0288,0.5123 ± 0.0310,0.1951 ± 0.0350,0.2009 ± 0.0360
LGBMClassifier,0.6734 ± 0.0151,0.6729 ± 0.0147,0.6663 ± 0.0275,0.6348 ± 0.0189,0.6498 ± 0.0163,0.3443 ± 0.0296,0.3451 ± 0.0294
LinearDiscriminantAnalysis,0.6723 ± 0.0173,0.6652 ± 0.0172,0.5871 ± 0.0348,0.6573 ± 0.0256,0.6194 ± 0.0220,0.3334 ± 0.0348,0.3357 ± 0.0352
LogisticRegression,0.6728 ± 0.0154,0.6672 ± 0.0152,0.6043 ± 0.0318,0.6522 ± 0.0230,0.6266 ± 0.0189,0.3364 ± 0.0308,0.3377 ± 0.0311
QuadraticDiscriminantAnalysis,0.6008 ± 0.0173,0.6043 ± 0.0170,0.6428 ± 0.0404,0.5531 ± 0.0173,0.5939 ± 0.0205,0.2059 ± 0.0336,0.2087 ± 0.0338
RandomForestClassifier,0.6871 ± 0.0132,0.6878 ± 0.0132,0.6956 ± 0.0242,0.6449 ± 0.0155,0.6690 ± 0.0146,0.3731 ± 0.0263,0.3743 ± 0.0264
RidgeClassifier,0.6723 ± 0.0169,0.6653 ± 0.0168,0.5878 ± 0.0347,0.6571 ± 0.0253,0.6197 ± 0.0215,0.3335 ± 0.0340,0.3357 ± 0.0344
SGDClassifier,0.6006 ± 0.0690,0.5969 ± 0.0539,0.5556 ± 0.3168,0.6867 ± 0.1777,0.5086 ± 0.1718,0.1964 ± 0.1098,0.2505 ± 0.0952
XGBClassifier,0.6680 ± 0.0159,0.6680 ± 0.0157,0.6677 ± 0.0312,0.6274 ± 0.0193,0.6464 ± 0.0179,0.3342 ± 0.0314,0.3353 ± 0.0314

In [6]:
clf = setup(data = X_train, target = y_train, remove_outliers = True,
           train_size = 0.8, session_id = 42, n_jobs = 10, fold = 10)

In [93]:
top_models = compare_models(turbo=False, sort = 'AUC', n)

In [7]:
model = create_model('rf')
model = tune_model(model, choose_better = True, n_iter = 100, optimize = 'AUC')

Fitting 10 folds for each of 100 candidates, totalling 1000 fits

In [8]:
model

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                       class_weight='balanced_subsample', criterion='gini',
                       max_depth=8, max_features='log2', max_leaf_nodes=None,
                       max_samples=None, min_impurity_decrease=0.005,
                       min_samples_leaf=2, min_samples_split=5,
                       min_weight_fraction_leaf=0.0, n_estimators=140,
                       n_jobs=10, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [7]:
model = create_model('catboost')
model = tune_model(model, choose_better = True, n_iter = 100, optimize = 'AUC')

Fitting 10 folds for each of 100 candidates, totalling 1000 fits

In [95]:
evaluate_model(model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [8]:
model.feature_importances_

array([0.50543076, 2.23571267, 0.        , 0.        , 1.00224053,
       0.71203227, 0.11859656, 1.1178996 , 0.02421599, 2.2098003 ,
       0.91446295, 0.20803542, 1.445908  , 2.63838285, 0.40473853,
       0.82900066, 0.69237275, 1.29208728, 3.11293084, 2.70459984,
       0.79029864, 0.52936754, 0.6459047 , 0.91166693, 1.85824419,
       0.90459647, 0.82179839, 1.52643517, 1.14571236, 2.43116476,
       0.64280159, 5.54939591, 0.96913868, 0.        , 0.        ,
       0.        , 1.61969288, 1.25080024, 1.68130862, 0.07605465,
       0.33045325, 1.22712629, 0.03559299, 1.70865873, 1.20377434,
       0.76442729, 1.79779762, 0.        , 1.07403101, 1.53795218,
       1.95616221, 3.51315235, 0.53937303, 5.9059114 , 4.43650151,
       1.65086845, 1.96952899, 1.09629226, 0.9720898 , 1.36721585,
       0.69945765, 1.45712338, 0.41406657, 0.7216471 , 1.33635792,
       1.63938224, 3.02503888, 1.23431665, 1.45889891, 1.11911618,
       0.77728576, 6.14307586, 1.36449383])

In [9]:
max_imp = model.feature_importances_.max()
relative_imp = (model.feature_importances_ / max_imp) * 100

In [10]:
imp_df = pd.DataFrame({
    'Feature' : X_train.columns,
    'Imp' : relative_imp
})

In [11]:
sort_imp = imp_df.sort_values(by = 'Imp', ascending=False)
sort_imp[0:20]

                                Feature         Imp
71              public_job_satisfaction  100.000000
53                 compensation_rewards   96.139321
31                                q31_7   90.335787
54                              welfare   72.219546
51                            promotion   57.188816
18                                q21_7   50.673814
66  organizational_citizenship_behavior   49.243066
19                                q21_8   44.026802
13                                q21_2   42.948889
29                                q31_5   39.575692
1                                    q2   36.394027
9                                   q12   35.972212
56                 performance_capacity   32.060958
50                          recruitment   31.843367
24                                  q29   30.249410
46                                  DM1   29.265431
43                                 dq11   27.814384
38                                  dq6   27.369166
55                             training   26.873646
65                       public_service   26.686668

보수 및 보상 100.0

직무 스트레스 : 나의 담당 업무에 대한 책임 범위가 불분명 하다 80.676594

공직 만족도 75.353379	

성과 관리 75.094575	

조직 몰입 73.839

직무 스트레스 : 공식 업무책임과 내 가치관 차이로 내적 갈등을 겪은 적이 있다. 69.5086

자원 제공 : 67.57

후생 복지 67.11

협업/의사소통 63.84

혁신 행동 63.601

직무만족ㄷ 58.862

리더십 57.430

공직 가치 55.830

조직 문화 : 우리 기관에서는 업무 수행 방식이나 관행을 개선하고자 상급자에게 자유롭게 건의할 수 있다. 55.569

의사 결졍 : 55.225

연공급적 임금체계(호봉제) 개편에 대해서 어떻게 생각하십니까 52.60

조직 문화 우리 부서에는 개성이 강하거나 생각이 다른 동료들이 서로 잘 협조하는 분위기가 있다 51.110

조직 문화 조직 구성원들은 매우 불만스런 태도를 갖고 있기 때문에 조직의 미래가 희망적이지 않다 48.576

변화 관리 47.711

교육 훈련/능력 발전 47.062

# 2. late_M

In [100]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(LM_X, LM_y, test_size = 0.2, random_state = 42, shuffle = False)

In [115]:
clf2 = setup(data = X_train, target = y_train, remove_outliers = True,
           train_size = 0.8, session_id = 42, n_jobs = 10, fold = 10)
top_models2 = compare_models(turbo=False, sort = 'AUC')

In [116]:
model = create_model('catboost')
model = tune_model(model, choose_better = True, n_iter = 100, optimize = 'AUC')

Fitting 10 folds for each of 100 candidates, totalling 1000 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [118]:
max_imp = model.feature_importances_.max()
relative_imp = (model.feature_importances_ / max_imp) * 100
imp_df = pd.DataFrame({
    'Feature' : X_train.columns,
    'Imp' : relative_imp
})
sort_imp = imp_df.sort_values(by = 'Imp', ascending=False)
sort_imp[0:20]

                                Feature         Imp
71              public_job_satisfaction  100.000000
69                           commitment   42.192280
25                                q31_1   41.611890
9                                   q12   31.634260
59                      decision_making   27.898787
21                               q21_10   26.401033
72                      quality_of_life   22.812536
51                            promotion   21.768881
47                                  DM5   20.746969
62           organizational_performance   20.093037
31                                q31_7   18.611614
64                      job_performance   18.594814
66  organizational_citizenship_behavior   17.798739
18                                q21_7   17.340581
53                 compensation_rewards   17.158820
23                               q21_12   16.641909
32                                  dq1   15.645452
56                 performance_capacity   15.049328
63               performance_management   14.929031
58                           leadership   14.903738

# 3. Early_M

In [109]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(EM_X, EM_y, test_size = 0.2, random_state = 42, shuffle = False)

In [120]:
clf3 = setup(data = X_train, target = y_train, remove_outliers = True,
           train_size = 0.8, session_id = 42, n_jobs = 10, fold = 10)
top_models3 = compare_models(turbo=False, sort = 'AUC')

In [121]:
model3 = create_model('catboost')
model3 = tune_model(model3, choose_better = True, n_iter = 100, optimize = 'AUC')

Fitting 10 folds for each of 100 candidates, totalling 1000 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [123]:
max_imp = model3.feature_importances_.max()
relative_imp = (model3.feature_importances_ / max_imp) * 100
imp_df = pd.DataFrame({
    'Feature' : X_train.columns,
    'Imp' : relative_imp
})
sort_imp = imp_df.sort_values(by = 'Imp', ascending=False)
sort_imp[0:20]

                                Feature         Imp
71              public_job_satisfaction  100.000000
69                           commitment   80.030083
65                       public_service   54.629888
53                 compensation_rewards   43.538804
68                public_service_values   38.449630
58                           leadership   38.414010
62           organizational_performance   35.738305
66  organizational_citizenship_behavior   35.228764
63               performance_management   34.358329
48                             resource   33.443523
27                                q31_3   33.439142
59                      decision_making   27.828119
72                      quality_of_life   27.610420
55                             training   27.252188
51                            promotion   26.813118
20                                q21_9   26.264069
67                  innovative_behavior   25.514297
54                              welfare   24.836575
64                      job_performance   22.898545
5                                  q6_1   22.502464